name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -U clean  package    -pl  ./start -am -Dmaven.test.skip=true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Build docker image with Maven
      run: mvn spring-boot:build-image -f ./start/pom.xml
      - name: tag with run id
      run: docker tag docker.io/yiezi/start:latest  docker.io/yiezi/start:${{ github.run_id }}
      - name: push
      run: docker push docker.io/yiezi/start:${{ github.run_id }}
      - name: change permissions
      run: chmod +x k8s/api/replace.sh
      - name: replace tag
      run: k8s/api/replace.sh API_TAG ${{ github.run_id }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch
      - name: Deploy to kuberentes
        if: steps.extract_branch.outputs.branch == 'master'
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f k8s/api/deployment.yaml